apiVersion: v1
kind: Service
metadata:
  name:  {{ include "postgres.headless.service.name" . | quote }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.headless.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.service.headless.port }}
    targetPort: {{ .Values.service.headless.targetPort }}
    protocol: {{ .Values.service.headless.protocol }}
    name: {{ .Values.service.headless.name }}
  selector: {{- include "postgres.selectorLabels" . | nindent 4 }}
