apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "postgres.configMap.name" . | quote }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
data: {{- tpl (.Files.Glob "config/*").AsConfig . | nindent 2 }}